### ISSUE TITLE
请求获取关于识别结果的更多信息时，返回的json数据中字符的x,y坐标为null

### ISSUE THREAD

**Issue by Yuri0314** [NJUOCR/universal_cnn#4]
从学院内网环境下载的镜像部署在了本地，然后把本地的32768端口绑定到了对应docker容器的4444端口之后，访问
> http://127.0.0.1:32768/?path=JDM_data/test0_tmp.png&remove_lines=1&verbose=1

返回的json数据里每个字符的x和y坐标都为null，如下图

![TIM截图20190331163708](https://user-images.githubusercontent.com/23535635/55286829-908ee700-53d3-11e9-8629-07e00592983d.jpg)

使用的图片是test_data中给出的测试图片，也用了其他的一些文书图片进行尝试仍然是这个问题。链接中的JDM_data是挂载的本地目录。

**Comment by AssKicker0214** [comment]
Fixed with commit 0df4d922600d06385fa7de52840f9be455c1e617
