### ISSUE TITLE
识别"北"字时返回的坐标信息为null

### ISSUE THREAD

**Issue by Yuri0314** [NJUOCR/universal_cnn#5]
识别图片对应位置为下图中第二行里“北闸口镇”的“北”字
![TIM截图20190401133949](https://user-images.githubusercontent.com/23535635/55305578-a6f47b80-5483-11e9-9854-a16524cf81d7.jpg)

识别后返回的json数据为：
![TIM截图20190401134204](https://user-images.githubusercontent.com/23535635/55305654-f3d85200-5483-11e9-9e51-c09219060f56.jpg)

**Comment by AssKicker0214** [comment]
`北`这个字在文字切分时被过度切分为两部分，系统会在第一次识别后尽可能发现这种被过度切分的字符，并且尝试将它们合并，然后再次识别。问题出在：** 合并后的字符丢失了位置信息。**

有关系统工作的具体原理，将在以后使用文档补充介绍。

---

 *Tips*

在请求中加入`auxiliary=1`可以查看识别过程的**辅助图像**：

1. 发起请求 `http://nju-vm:4444/?path=test_data/test0.png&verbose=1&auxiliary=1`，注意添加**auxiliary**字段；
2. 获取辅助图像 `http://nju-vm:4444/static/auxiliary.jpg`，该图像为最近一次识别的内容。其中，被合并的字符使用**蓝色线条**包裹，如：
![image](https://user-images.githubusercontent.com/17632347/55310925-46216f00-5494-11e9-84ec-e167c1e65290.png)
