### ISSUE TITLE
单独标题识别 

### ISSUE THREAD

**Issue by yaolinxia** [NJUOCR/universal_cnn#7]
标题识别切分行不准确，可能导致切分字错误，标题识别出来的结果为空。在宣判笔录这一类别中，1260个数据， 大约识别准确率为90.5%， 其中为空的占5%。

**Comment by AssKicker0214** [comment]
当图片中的最后一行与图片底部没有间隙时，会导致最后一行无法被正确切分出来，这是一个边界值错误
