### ISSUE TITLE
请求的json数据中，有的字符为空字符

### ISSUE THREAD

**Issue by Yuri0314** [NJUOCR/universal_cnn#8]
使用给的测试图片进行请求时，得到的json数据里有的字符值为空字符，如下图
![TIM截图20190403214850](https://user-images.githubusercontent.com/23535635/55484051-5c792780-565a-11e9-9b47-cf57b1f5aca7.jpg)
这是什么原因？

**Comment by AssKicker0214** [comment]
这是一个好问题，对比识别过程的辅助图像，可以发现系统在切分文字的时候对双引号进行了过度的切分，结果会预测为两个单引号，预测结果会在后处理过程中进行修正，将这两个单引号合并为一个双引号。*在目前的实现中，会将前一个文字更改为双引号，而后一个文字更改为空字符*，** 我不打算去修复这个问题**，因为后处理的整个模块都计划使用RNN+NLP的方式完全重构，当前的后处理会被抛弃。

![image](https://user-images.githubusercontent.com/17632347/55484263-c5f93600-565a-11e9-8598-5110ef39281a.png)

> 关于如何获取辅助图像可以参考这个[Issue](https://github.com/NJUOCR/universal_cnn/issues/5#issuecomment-478478289)
