### ISSUE TITLE
批量预测图片数据时，中途停止，出现错误

### ISSUE THREAD

**Issue by yaolinxia** [NJUOCR/universal_cnn#9]
详细，见[](https://raw.githubusercontent.com/yaolinxia/img_resource/master/multi-input attention/2019-05-10 15-16-54屏幕截图.png)

**Comment by AssKicker0214** [comment]
![error](https://raw.githubusercontent.com/yaolinxia/img_resource/master/multi-input%20attention/2019-05-10%2015-16-54屏幕截图.png)

**Comment by AssKicker0214** [comment]
**产生错误的部分**：后处理过程的其中一步是对每一行的文字计算中心点的**回归线**，这个**回归线**用来为每一个字符提供位置参照，比如区别`，`（逗号）和`‘`（右单引号），它们长相一样，只有相对位置不同。

当某行文字只有一个字符时（*或者说只被切出一个字符时*），该行没有办法计算回归线。导致斜率`self.a`和截距`self.b`为`NoneType`。

需要修复的代码块[在这里](https://github.com/NJUOCR/universal_cnn/blob/e75caec7721a56a88418829f3bf7a8f5b238aaa5/utils/utext.py#L420)

我会尽快修复这个问题。

**Comment by yaolinxia** [comment]
使用最新版本的项目，进行预测，问题解决，之前使用的是老版本的。

**Comment by AssKicker0214** [comment]
好的，我已进行边界测试，任何一行都不会被切分为一个字符，至少会包含一个空白字符。回归线永远可以被计算。**这种情况下，可能会计算不准确**
